POST http://localhost:3003/users
content-type: application/json

{
    "name": "Usuario5",
	"email": "Usuario5@Usuario5.com",
    "password": "1232"
}
###
GET http://localhost:3003/users
### 
POST http://localhost:3003/products
content-type: application/json

{
    "name": "ImagemparaTeste",
	"price": 60,
    "imageurl": "https://i.picsum.photos/id/10/2500/1667.jpg?hmac=J04WWC_ebchx3WwzbM-Z4_KC_LeLBWr5LZMaAkWkF68"
}
###
GET http://localhost:3003/products
###
GET http://localhost:3003/products/2
###
POST http://localhost:3003/purchases
content-type: application/json

{
    "user_id": "1",
	"product_id ": "3",
    "quantity": "3"
}
###