###registrar outfits
POST http://localhost:3003/outfit/sign
Content-Type: application/json

{
    "name": "Roupa teste geral12",
    "tags": ["colorido", "metal", "delicado", "estampas", "passeio"]
}
### Cadastrar roupa
POST http://localhost:3003/outfit/signout
Content-Type: application/json

{
    "name": "Roupa teste 06 only1236"
}
### Adicionar tags
POST http://localhost:3003/outfit/tag
Content-Type: application/json

{
    "tags": "Tag teste 023336"
}

###Linkar novas tags a robes
POST http://localhost:3003/outfit/link
Content-Type: application/json

{
    "name": "Roupa teste geral1",
    "tags": "metal"
}

###Ver todas as tags
GET http://localhost:3003/outfit/tags

###
GET http://localhost:3003/outfit/