POST http://localhost:3003/signup
Content-Type: application/json

{
    "name":"Usuario03",
	"email": "Usuario03@usua03.com",
	"password": "12301234"
}
###
POST http://localhost:3003/login
Content-Type: application/json

{
	"email": "Usuario03@usua03.com",
	"password": "12301234"
}
###
GET http://localhost:3003/user/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk1NDgxNjNmLTQ1ODctNGIwYS05YjE1LTBhMDA4NjRjZDU3ZSIsImlhdCI6MTY2MzE4NTgzMywiZXhwIjoxNjYzMTg4ODMzfQ.S_Y7bfH9wfFuOQyaK2Z4KVMyZ8LeBIvulTBjSZNf7oQ
###
GET http://localhost:3003/user/111fea13-0376-4172-b4e3-8894ec58ff1b
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk1NDgxNjNmLTQ1ODctNGIwYS05YjE1LTBhMDA4NjRjZDU3ZSIsImlhdCI6MTY2MzE4NTgzMywiZXhwIjoxNjYzMTg4ODMzfQ.S_Y7bfH9wfFuOQyaK2Z4KVMyZ8LeBIvulTBjSZNf7oQ
###
POST http://localhost:3003/recipe
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk1NDgxNjNmLTQ1ODctNGIwYS05YjE1LTBhMDA4NjRjZDU3ZSIsImlhdCI6MTY2MzE4NTgzMywiZXhwIjoxNjYzMTg4ODMzfQ.S_Y7bfH9wfFuOQyaK2Z4KVMyZ8LeBIvulTBjSZNf7oQ
Content-Type: application/json

{
	"title": "receita01user01",
	"description": "descrição receita02"
}
###
GET http://localhost:3003/recipe/3219c573-54fc-4215-9d9b-829c056503b4
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk1NDgxNjNmLTQ1ODctNGIwYS05YjE1LTBhMDA4NjRjZDU3ZSIsImlhdCI6MTY2MzE4NTgzMywiZXhwIjoxNjYzMTg4ODMzfQ.S_Y7bfH9wfFuOQyaK2Z4KVMyZ8LeBIvulTBjSZNf7oQ