### Endpoint de teste
GET http://localhost:3003/ping
###
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "UserTeste01",
    "email": "UserTeste01@gmail.com",
    "password": "abc123"
}
### 2) Login
    # "email": "astrodev@gmail.com",
    # "password": "bananinha"
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "astrodev@gmail.com",
    "password": "bananinha"
}
###
POST http://localhost:3003/shows/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2NDQ4NzkyOSwiZXhwIjoxNjY0NTc0MzI5fQ.NuhEBhhXzk1LsaWxKWGfxT3rXvWfSa73JOM0ULcAaJM

{
    "band": "Banda teste 01",
    "starts_at": "2028-12-26"
}

###
GET http://localhost:3003/shows

###
POST http://localhost:3003/shows/claim
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI2NTQxMDI0LWFmYWMtNDFkZS04MDNjLWE0ODJlNTIxMjBmYiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjQ0ODc5NzEsImV4cCI6MTY2NDU3NDM3MX0.-kEByhdQrwMBhTjbYDzCcnwihUl9lbPtSkyDGQGIHsg

{
    "show_id": "203"
}

###
POST http://localhost:3003/shows/unclaim
Content-Type: application/json
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI2NTQxMDI0LWFmYWMtNDFkZS04MDNjLWE0ODJlNTIxMjBmYiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjQ0ODc5NzEsImV4cCI6MTY2NDU3NDM3MX0.-kEByhdQrwMBhTjbYDzCcnwihUl9lbPtSkyDGQGIHsg

{
    "show_id": "203"
}

###