POST http://localhost:3003/user
content-type: application/json

{
    "name": "Parce2l32 pontocom",
	"nickname":"Pa2r32cel",
	"email": "Par2c@dd32ev.co"
}
###
GET http://localhost:3003/user/2
###
PUT http://localhost:3003/user/edit/1
content-type: application/json

{
    "name": "Astro Dev34",
	"nickname": "astrodev34"
}
###
POST http://localhost:3003/task
content-type: application/json

{
"title": "Criar11 banco dos alunos",
"description": "Devem11os criar o banco dos alunos para o módulo do backend",
"limitDate": "04/05/2020",
"creatorUserId": "018"
}
###
GET http://localhost:3003/task/1
###

